# Generated by Django 6.0.4 on 2026-04-19 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Otag ady')),
                ('classroom_type', models.CharField(choices=[('LAB', 'Laboratoriya'), ('LEC', 'Leksiya zaly'), ('SIM', 'Adaty otag')], max_length=3, verbose_name='Otag gornusi')),
                ('capacity', models.IntegerField(default=30, verbose_name='Kuwwatlylygy')),
                ('building', models.CharField(blank=True, max_length=50, verbose_name='Bina')),
            ],
            options={
                'verbose_name': 'Synp otagy',
                'verbose_name_plural': 'Synp otaglary',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ady')),
                ('short_name', models.CharField(blank=True, max_length=20, verbose_name='Gysgaca ady')),
            ],
            options={
                'verbose_name': 'Kafedra',
                'verbose_name_plural': 'Kafedralar',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Jubet belgisi')),
                ('start_time', models.TimeField(verbose_name='Baslanyan wagty')),
                ('end_time', models.TimeField(verbose_name='Gutaryan wagty')),
                ('shift', models.IntegerField(choices=[(1, '1-nji calsyk'), (2, '2-nji calsyk')], default=1, verbose_name='Calsyk')),
            ],
            options={
                'verbose_name': 'Wagt jubudi',
                'verbose_name_plural': 'Wagt jubetleri',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Topar ady')),
                ('group_type', models.CharField(choices=[('TM', 'Turkmen'), ('EN', 'Inlis'), ('RU', 'Rus')], default='TM', max_length=2, verbose_name='Topar gornusi')),
                ('course', models.IntegerField(default=1, verbose_name='Kurs')),
                ('student_count', models.IntegerField(default=25, verbose_name='Talyp sany')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.department', verbose_name='Kafedra')),
            ],
            options={
                'verbose_name': 'Topar',
                'verbose_name_plural': 'Toparlar',
                'ordering': ['course', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Dersinin ady')),
                ('short_name', models.CharField(blank=True, max_length=50, verbose_name='Gysgaca ady')),
                ('subject_type', models.CharField(choices=[('LAB', 'Laboratoriya'), ('LEC', 'Leksiya zaly'), ('SIM', 'Adaty otag')], max_length=3, verbose_name='Ders gornusi')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.department', verbose_name='Kafedra')),
            ],
            options={
                'verbose_name': 'Ders',
                'verbose_name_plural': 'Dersler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ady')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiyasy')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Atasyn ady')),
                ('can_teach_english', models.BooleanField(default=False, verbose_name='Inlisce okadyp bilyar')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Wezipesi')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.department', verbose_name='Kafedra')),
            ],
            options={
                'verbose_name': 'Mugallym',
                'verbose_name_plural': 'Mugallymlar',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Duşenbe'), ('TUE', 'Sişenbe'), ('WED', 'Çarşenbe'), ('THU', 'Penşenbe'), ('FRI', 'Anna'), ('SAT', 'Şenbe'), ('SUN', 'Ýekşenbe')], max_length=3, verbose_name='Gun')),
                ('week_type', models.CharField(choices=[('ODD', 'Tak hepde'), ('EVEN', 'Juft hepde'), ('BOTH', 'Her hepde')], default='BOTH', max_length=4, verbose_name='Hepde gornusi')),
                ('subgroup', models.CharField(choices=[('FULL', 'Doly topar'), ('SUB1', '1-nji kici topar'), ('SUB2', '2-nji kici topar')], default='FULL', max_length=4, verbose_name='Kici topar')),
                ('lesson_type', models.CharField(choices=[('LAB', 'Laboratoriya'), ('LEC', 'Leksiya zaly'), ('SIM', 'Adaty otag')], max_length=3, verbose_name='Sapak gornusi')),
                ('language', models.CharField(choices=[('TM', 'Turkmence'), ('EN', 'Inlisce'), ('RU', 'Rusca')], default='TM', max_length=2, verbose_name='Dil')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.classroom', verbose_name='Synp otagy')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.group', verbose_name='Topar')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.subject', verbose_name='Ders')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.teacher', verbose_name='Mugallym')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.timeslot', verbose_name='Wagt jubudi')),
            ],
            options={
                'verbose_name': 'Sapak',
                'verbose_name_plural': 'Sapaklyk',
            },
        ),
    ]
