# Generated by Django 6.0.4 on 2026-04-21 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_type', models.CharField(choices=[('LAB', 'Laboratoriya'), ('LEC', 'Leksiya zaly'), ('SIM', 'Adaty otag')], max_length=3, verbose_name='Sapak gornusi')),
                ('hours_per_week', models.IntegerField(default=1, help_text='BOTH hepde ucin 1, LAB ucin 2 (tak+juft)', verbose_name='Hepde jubutleri')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum', to='schedule.group', verbose_name='Topar')),
                ('preferred_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.teacher', verbose_name='Saylanyan mugallym')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.subject', verbose_name='Ders')),
            ],
            options={
                'verbose_name': 'Okuw plany',
                'verbose_name_plural': 'Okuw planlary',
                'unique_together': {('group', 'subject', 'lesson_type')},
            },
        ),
    ]
